export type ReportStatus = 'Draft' | 'PendingSignature' | 'Published' | 'Amended' | 'Cancelled';

export type SignatureType = 'Typed' | 'UploadedImage' | 'Digital';
export type ReportPdfMode = 'AutoGenerated' | 'Uploaded';
export type ReportAuditAction = 'Created' | 'Edited' | 'Signed' | 'Published' | 'Resent' | 'Amended';

export interface ReportCriticalFlag {
  testId: string;
  parameter: string;
  value: string;
}

export interface ReportAuditEvent {
  at: string;
  by: string;
  action: ReportAuditAction;
  notes?: string;
}

export interface ReportPathologist {
  name: string;
  registrationNo?: string;
  signedAt?: string;
}

export interface ReportPdfData {
  mode: ReportPdfMode;
  fileName?: string;
  dataUrl?: string;
}

export interface Report {
  reportId: string;
  bookingId: string;
  sampleId: string;
  patientId: string;
  testIds: string[];
  packageId?: string;
  createdAt: string;
  updatedAt: string;
  status: ReportStatus;
  generatedBy: string;
  pathologist: ReportPathologist;
  signatureType: SignatureType;
  signatureImageDataUrl?: string;
  remarks?: string;
  testRemarks?: Record<string, string>;
  criticalFlags: ReportCriticalFlag[];
  criticalHandled?: boolean;
  criticalHandledNote?: string;
  pdf: ReportPdfData;
  audit: ReportAuditEvent[];
}
